### ISSUE TITLE
Promote papers

### ISSUE THREAD

**Issue by bblockwood** [bblockwood/bblockwood.github.io#1]
The goal of this issue is to carry out the following changes on the both the *papers* and *research* pages (which are similar to each other — for background, the *research* page is the outward-facing one that doesn't contain links to copyright-protected journal articles, while *papers* is the quieter version that I know how to access, which does contain such links.)

1. Promote the JEP soda tax paper to be in the "forthcoming" section. 
2. Add to the "Selected work in progress" section the following:
  1. "Generalized Capital Taxation with Sufficient Statistics" joint with Dmitry and with Antoine Ferey
  2. "What Is the Optimal Implicit Lottery Tax?" joint with Dmitry and Hunt Allcott

**Comment by bblockwood** [comment]
@afras-sial thanks for these edits, this is looking nice. Two modifications:

1. I realize I mistyped above, I didn't really mean create a new "Forthcoming" section, I just meant move JEP up to the "Research Publications" section. So can you please adjust accordingly? Sorry for the mistake on my part. 
2. I should have specified — for the newly added papers (points 3 and 4 above) please switch the co-author name order to be alphabetical by last name. 

Then in general, once you have carried out a task like this, please ping me by posting an update to this issue saying "@bblockwood: I've done this" or whatever, and I'll check out the result. 

Thank you!

**Comment by afras-sial** [comment]
@bblockwood No worries and thanks for the feedback. I just updated the branch with the edits.

**Comment by bblockwood** [comment]
Perfect, thanks @afras-sial! I'll check it out.

**Comment by bblockwood** [comment]
This is awesome, thanks again for your work. Two tiny last requests:

1. Move the JEP article to second rather than first place in the _Research Publications_ section.
2. Move the two projects newly added to *Selected Work in Progress* to the top of that section, rather than the bottom. 

Then go ahead and commit, merge that branch into the master one, and push to GitHub. After doing that, the changes should be live at benlockwood.com. 

Thanks again!

**Comment by afras-sial** [comment]
@bblockwood Just finished doing this. It looks like the changes are live.

**Comment by bblockwood** [comment]
Looks great -- thanks @afras-sial!
