### ISSUE TITLE
Create "data" page

### ISSUE THREAD

**Issue by bblockwood** [bblockwood/bblockwood.github.io#2]
The goal of this issue is to create a "Data" page that is properly linked to the other pages, and appears in the menu bar between "Research" and "CV". Let's create one link to the commitment_survey.zip file uploaded last week, and then I'll add a blurb explaining what it is. (No rush on this, just when time allows.)

**Comment by afras-sial** [comment]
@bblockwood Just created this page. Let me know if I should make any changes.

**Comment by bblockwood** [comment]
Looks good, thanks!
